### ISSUE TITLE
jQuery ($) is not recognized in putsreq.com

### ISSUE THREAD

**Issue by matan7890** [phstc/putsreq#23]
It seems like jquery is not loaded or something like that, because it is not identified in the ruby's javascript interpreter. To reproduce, just use the code from the readme.md:
```
$.get('https://putsreq.com', function(data) {
  alert(data.message);
  // => 'Hello World'
});
```
It will break when you try to access the bucket with response:
> $ is not defined

**Comment by phstc** [comment]
hi @matan7890 

`jQuery` isn't available in the response builder context. Not sure if I could follow what you are trying to do, could you link me your bucket?

**Comment by sadortun** [comment]
@phstc I think @matan7890  mean that your example is not "working" because you did not include  jQuery lib. See PR #25

**Comment by phstc** [comment]
>  Not sure if I could follow what you are trying to do, could you link me your bucket?

@matan7890 I meant that I didn't understand that, because I couldn't see a use case for that. PutsReq handles requests, the JavaScript used in the response builder is only to handle requests. Why a response builder should make a request to PutsReq?

```javascript
$.get('https://putsreq.com', function(data) {
  alert(data.message);
  // => 'Hello World'
});
```

`jQuery` is a library that manipulates DOM etc, why should we add it to handle requests?

**Comment by phstc** [comment]
Oh, nvm. I got it, it's just because of the example on the README, it isn't to make it available on the response builder.

Thanks
